package semanal;

public enum NodeType {
    ADITIVNI_IZRAZ, BIN_I_IZRAZ, BIN_ILI_IZRAZ, BIN_XILI_IZRAZ,
    CAST_IZRAZ, DEFINICIJA_FUNKCIJE, DEKLARACIJA,
    DEKLARACIJA_PARAMETRA, IME_TIPA, INICIJALIZATOR,
    INIT_DEKLARATOR, IZRAVNI_DEKLARATOR, IZRAZ,
    IZRAZ_NAREDBA, IZRAZ_PRIDRUZIVANJA, JEDNAKOSNI_IZRAZ,
    LISTA_ARGUMENATA, LISTA_DEKLARACIJA, LISTA_INIT_DEKLARATORA,
    LISTA_IZRAZA_PRIDRUZIVANJA, LISTA_NAREDBI, LISTA_PARAMETARA,
    LOG_I_IZRAZ, LOG_ILI_IZRAZ, MULTIPLIKATIVNI_IZRAZ,
    NAREDBA, NAREDBA_GRANANJA, NAREDBA_PETLJE,
    NAREDBA_SKOKA, ODNOSNI_IZRAZ, POSTFIKS_IZRAZ,
    PRIJEVODNA_JEDINICA, PRIMARNI_IZRAZ, SLOZENA_NAREDBA,
    SPECIFIKATOR_TIPA, UNARNI_IZRAZ, UNARNI_OPERATOR,
    VANJSKA_DEKLARACIJA
}